piVersion: v1
kind: Service
metadata:
  name: vprofile-service
spec:
  type: NodePort
  selector:
    app: vprofile
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30007
                                              
